path:
  meta_file_train: "../../data/augmented_data/LibriTTS-original/train.txt"
  meta_file_val: "../../data/augmented_data/LibriTTS-original/val.txt"
  speaker_map_file: "../../data/augmented_data/LibriTTS-original/speakers.json"
  feature_dir: "../../data/augmented_data/LibriTTS-original"
  stats_file: "../../data/augmented_data/LibriTTS-original/stats.json"
  sentiment_file: "../../data/original/LibriTTS/sentiment_scores_libri-tts.csv"

properties:
  pitch_feature_level: "phoneme_level" # support 'phoneme_level' or 'frame_level'
  energy_feature_level: "phoneme_level" # support 'phoneme_level' or 'frame_level'
  n_mel_channels: 80
  max_wav_value: 32768.0
  sampling_rate: 22050
  stft_hop_length: 256

preprocessing:
  text_cleaners: ["english_cleaners"]
