path:
  base_dir: "../../data/LibriTTS.tar"
  meta_file_train: "train.txt"
  meta_file_val: "val.txt"
  speaker_map_file: "speakers.json"
  feature_dir: ""
  stats_file: "stats.json"
  sentiment_file: "sentiment_scores.csv"

properties:
  pitch_feature_level: "phoneme_level" # support 'phoneme_level' or 'frame_level'
  energy_feature_level: "phoneme_level" # support 'phoneme_level' or 'frame_level'
  n_mel_channels: 80
  max_wav_value: 32768.0
  sampling_rate: 22050
  stft_hop_length: 256
  num_sentiments: 3

preprocessing:
  lexicon_path: "../../lexicon/librispeech-lexicon.txt"
  text_cleaners: ["english_cleaners"]
