path:
  meta_file_train: "../../data/LibriTTS/train.txt"
  meta_file_val: "../../data/LibriTTS/val.txt"
  speaker_map_file: "../../data/LibriTTS/speakers.json"
  feature_dir: "../../data/LibriTTS"
  stats_file: "../../data/LibriTTS/stats.json"
  sentiment_file: "./overrides/sentiment_scores_override_all_neg.csv"

properties:
  pitch_feature_level: "phoneme_level" # support 'phoneme_level' or 'frame_level'
  energy_feature_level: "phoneme_level" # support 'phoneme_level' or 'frame_level'
  n_mel_channels: 80
  max_wav_value: 32768.0
  sampling_rate: 22050
  stft_hop_length: 256
  num_sentiments: 3

preprocessing:
  lexicon_path: "../../lexicon/librispeech-lexicon.txt"
  text_cleaners: ["english_cleaners"]
